-- Generated by ghost_client/tools/make_hwid.py -- do not edit by hand.
--
-- The Login Start extras for this bot, already encrypted. `fields` are the eight
-- base64 payloads in the order the server reads them (os name, hostname, discord id,
-- MAC, CPU, board UUID, GPUs, disks); connection.lua prefixes each with \1 and frames
-- it as a Java writeUTF string (u16 byte count, then the bytes).
--
-- `locale` goes in FRONT of the username, not after it -- see connection.lua.
--
-- Regenerate with:
--     python -m ghost_client.tools.make_hwid --seed=ghost-galaxy-oc

return {
  locale = "ru_RU",
  fields = {
    "ILmIrFEfCSSvSzxTZXJzKIMKkF1bbeonVAlwXGZ0VdU=", -- os_name
    "Qg/xiRQOC2MiubJ3ouTQq8zr5PxYB14LRjgC5IR7UyA=", -- hostname
    "RxAsO5Fhm3wX9SYv/1MfKU8THb5S346n", -- discord_id
    "0arTY6+eaXS/J9XzKWeGsqd5wpPYutx6A41HLWmCFJjxIw8ko/gzLA==", -- mac
    "7W4YyYAuqNlP8Xx2MLeretqxa9wCOJtIh0N2IwqHdUfqYYvmM7YM4+fgs0w4cByYojLcvNwaDbv1CaC15WAqJrWN2Vg0QnC+pMspzZweIvE=", -- cpu
    "tY5w/bqr/gAryvWqWlX5ayjD0OyRLl2NQNLP5G0PpxkHphVekDawzlq5aIKEFXvIAQ9YxYqPGNw=", -- board_uuid
    "tl1lhSwEn9T93KSQf7qPgtYV7x+8wuaRZRz1Osu8kLnerIKlD4o3uW+aNDztfV84GCCaojC7jfD+XLOSCaXDJs+8v22TD+VW", -- gpus
    "aYK1IKZu3/zElX9lfMW1SEU8UtOgi+iQZE5Fn161AMOZyUEBCfqJo0Uag8S4DQR8GSNuVq2qiJA=", -- disks
  },
}
